apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: inspektor-gadget
  namespace: gadget
spec:
  labelLimit: 63
  labelNameLengthLimit: 511
  labelValueLengthLimit: 1023
  namespaceSelector:
    matchNames:
      - gadget
  selector:
    matchLabels:
      k8s-app: gadget
  podMetricsEndpoints:
    - path: /metrics
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_k8s_app
          action: keep
          regex: gadget
        - sourceLabels:
            - __address__
          action: replace
          regex: '([^:]+)(?::\d+)?'
          replacement: '$1:2224'
          targetLabel: __address__
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
      metricRelabelings:
        - action: labeldrop
          regex: (pod|container|namespace)
        - targetLabel: job
          replacement: inspektor-gadget

